<?xml version="1.0" encoding="UTF-8"?>

<!--Autogenerated by Cloudera Manager-->
<configuration>
  <!--'dfs.nameservices', originally set to 'zxnameservice1' (non-final), is overridden below by a safety valve-->
  <property>
    <name>dfs.client.failover.proxy.provider.zxnameservice1</name>
    <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
  </property>
  <property>
    <name>dfs.ha.automatic-failover.enabled.zxnameservice1</name>
    <value>true</value>
  </property>
  <property>
    <name>ha.zookeeper.quorum</name>
    <value>401a27rs05hdp206.sxmcc:2181,401a27rs06hdp205.sxmcc:2181,401b02rs04hdp217.sxmcc:2181</value>
  </property>
  <property>
    <name>dfs.ha.namenodes.zxnameservice1</name>
    <value>namenode17,namenode25</value>
  </property>
  <property>
    <name>dfs.namenode.rpc-address.zxnameservice1.namenode17</name>
    <value>401a27rs04hdp207.sxmcc:8020</value>
  </property>
  <property>
    <name>dfs.namenode.servicerpc-address.zxnameservice1.namenode17</name>
    <value>401a27rs04hdp207.sxmcc:8022</value>
  </property>
  <property>
    <name>dfs.namenode.http-address.zxnameservice1.namenode17</name>
    <value>401a27rs04hdp207.sxmcc:9870</value>
  </property>
  <property>
    <name>dfs.namenode.https-address.zxnameservice1.namenode17</name>
    <value>401a27rs04hdp207.sxmcc:9871</value>
  </property>
  <property>
    <name>dfs.namenode.rpc-address.zxnameservice1.namenode25</name>
    <value>401b02rs03hdp218.sxmcc:8020</value>
  </property>
  <property>
    <name>dfs.namenode.servicerpc-address.zxnameservice1.namenode25</name>
    <value>401b02rs03hdp218.sxmcc:8022</value>
  </property>
  <property>
    <name>dfs.namenode.http-address.zxnameservice1.namenode25</name>
    <value>401b02rs03hdp218.sxmcc:9870</value>
  </property>
  <property>
    <name>dfs.namenode.https-address.zxnameservice1.namenode25</name>
    <value>401b02rs03hdp218.sxmcc:9871</value>
  </property>
  <property>
    <name>dfs.replication</name>
    <value>3</value>
  </property>
  <property>
    <name>dfs.blocksize</name>
    <value>134217728</value>
  </property>
  <property>
    <name>dfs.client.use.datanode.hostname</name>
    <value>false</value>
  </property>
  <property>
    <name>fs.permissions.umask-mode</name>
    <value>022</value>
  </property>
  <!--'dfs.client.block.write.locateFollowingBlock.retries', originally set to '7' (non-final), is overridden below by a safety valve-->
  <property>
    <name>dfs.encrypt.data.transfer.algorithm</name>
    <value>3des</value>
  </property>
  <property>
    <name>dfs.encrypt.data.transfer.cipher.suites</name>
    <value>AES/CTR/NoPadding</value>
  </property>
  <property>
    <name>dfs.encrypt.data.transfer.cipher.key.bitlength</name>
    <value>256</value>
  </property>
  <property>
    <name>dfs.namenode.acls.enabled</name>
    <value>true</value>
  </property>
  <property>
    <name>dfs.client.read.shortcircuit</name>
    <value>false</value>
  </property>
  <property>
    <name>dfs.domain.socket.path</name>
    <value>/var/run/hdfs-sockets/dn</value>
  </property>
  <property>
    <name>dfs.client.read.shortcircuit.skip.checksum</name>
    <value>false</value>
  </property>
  <property>
    <name>dfs.client.domain.socket.data.traffic</name>
    <value>false</value>
  </property>
  <property>
    <name>dfs.datanode.hdfs-blocks-metadata.enabled</name>
    <value>true</value>
  </property>
  <property>
    <name>dfs.block.access.token.enable</name>
    <value>true</value>
  </property>
  <property>
    <name>dfs.namenode.kerberos.principal</name>
    <value>hdfs/_HOST@SXMCC.COM</value>
  </property>
  <property>
    <name>dfs.namenode.kerberos.internal.spnego.principal</name>
    <value>HTTP/_HOST@SXMCC.COM</value>
  </property>
  <property>
    <name>dfs.datanode.kerberos.principal</name>
    <value>hdfs/_HOST@SXMCC.COM</value>
  </property>
  <property>
    <name>dfs.client.block.write.locateFollowingBlock.retries</name>
    <value>20</value>
  </property>
  <property>
    <name>dfs.nameservices</name>
    <value>zxnameservice1,nameservice-newnewremote1</value>
  </property>
  <property>
    <name>dfs.client.failover.proxy.provider.nameservice-newnewremote1</name>
    <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
  </property>
  <property>
    <name>dfs.ha.automatic-failover.enabled.nameservice-newnewremote1</name>
    <value>true</value>
  </property>
  <property>
    <name>dfs.ha.namenodes.nameservice-newnewremote1</name>
    <value>namenode1357,namenode1358</value>
  </property>
  <property>
    <name>dfs.namenode.rpc-address.nameservice-newnewremote1.namenode1357</name>
    <value>za2301b03rs07hdp1357.sxmcc:8020</value>
  </property>
  <property>
    <name>dfs.namenode.servicerpc-address.nameservice-newnewremote1.namenode1357</name>
    <value>za2301b03rs07hdp1357.sxmcc:8022</value>
  </property>
  <property>
    <name>dfs.namenode.rpc-address.nameservice-newnewremote1.namenode1358</name>
    <value>za2301b03rs08hdp1358.sxmcc:8020</value>
  </property>
  <property>
    <name>dfs.namenode.servicerpc-address.nameservice-newnewremote1.namenode1358</name>
    <value>za2301b03rs08hdp1358.sxmcc:8022</value>
  </property>
</configuration>
